/**
 * GLR 4 Schools
 * **NUMBER ONE TOPIC IS HOW BEST TO IMPLEMENT THESE API so that only data is segregated by school.**  Need to implement a form of authentication check PER SCHOOL. Is there a way to leverage the authorisation process implement by Group Call Xporter? This is the full set of API for GLR 4 Schools. Security definitions and exqmples need to be added.
 *
 * The version of the OpenAPI document: 1.0.1-oas3
 * Contact: john@greatlittlerewards.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import LineItem from './LineItem';
import User from './User';

/**
 * The Body model module.
 * @module //Body
 * @version 1.0.1-oas3
 */
class Body {
    /**
     * Constructs a new <code>Body</code>.
     * @alias module://Body
     */
    constructor() {

        Body.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {
    }

    /**
     * Constructs a <code>Body</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module://Body} obj Optional instance to populate.
     * @return {module://Body} The populated <code>Body</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body();

            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('lineItems')) {
                obj['lineItems'] = ApiClient.convertToType(data['lineItems'], [LineItem]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:User} user
 */
Body.prototype['user'] = undefined;

/**
 * @member {Array.<module:LineItem>} lineItems
 */
Body.prototype['lineItems'] = undefined;






export default Body;

