/**
 * GLR 4 Schools
 * **NUMBER ONE TOPIC IS HOW BEST TO IMPLEMENT THESE API so that only data is segregated by school.**  Need to implement a form of authentication check PER SCHOOL. Is there a way to leverage the authorisation process implement by Group Call Xporter? This is the full set of API for GLR 4 Schools. Security definitions and exqmples need to be added.
 *
 * The version of the OpenAPI document: 1.0.1-oas3
 * Contact: john@greatlittlerewards.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import LineItem from './LineItem';

/**
 * The Cart model module.
 * @module //Cart
 * @version 1.0.1-oas3
 */
class Cart {
    /**
     * Constructs a new <code>Cart</code>.
     * @alias module://Cart
     * @param orderId {String}
     */
    constructor(orderId) {

        Cart.initialize(this, orderId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orderId) {
        obj['orderId'] = orderId;
    }

    /**
     * Constructs a <code>Cart</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module://Cart} obj Optional instance to populate.
     * @return {module://Cart} The populated <code>Cart</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Cart();

            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
            }
            if (data.hasOwnProperty('totalPoints')) {
                obj['totalPoints'] = ApiClient.convertToType(data['totalPoints'], 'Number');
            }
            if (data.hasOwnProperty('lineItems')) {
                obj['lineItems'] = ApiClient.convertToType(data['lineItems'], [LineItem]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} orderId
 */
Cart.prototype['orderId'] = undefined;

/**
 * @member {Number} totalPoints
 */
Cart.prototype['totalPoints'] = undefined;

/**
 * @member {Array.<module:LineItem>} lineItems
 */
Cart.prototype['lineItems'] = undefined;






export default Cart;

