/**
 * GLR 4 Schools
 * **NUMBER ONE TOPIC IS HOW BEST TO IMPLEMENT THESE API so that only data is segregated by school.**  Need to implement a form of authentication check PER SCHOOL. Is there a way to leverage the authorisation process implement by Group Call Xporter? This is the full set of API for GLR 4 Schools. Security definitions and exqmples need to be added.
 *
 * The version of the OpenAPI document: 1.0.1-oas3
 * Contact: john@greatlittlerewards.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "./ApiClient";
import Menu from './Menu';
import User from './User';

/**
* ExperienceApi service.
* @module //ExperienceApiApi
* @version 1.0.1-oas3
*/
export default class ExperienceApiApi {

    /**
    * Constructs a new ExperienceApiApi.
    * @alias module://ExperienceApiApi
    * @class
    * @param {module:/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getNavigation operation.
     * @callback module://ExperienceApiApi~getNavigationCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:Menu>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a 2 level menu definition
     * returns a menu object that defines how we expect collections to be displayed
     * @param {module://ExperienceApiApi~getNavigationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:Menu>}
     */
    getNavigation(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Menu];
      return this.apiClient.callApi(
        '/store/collection/getNavigation', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the loginPost operation.
     * @callback module://ExperienceApiApi~loginPostCallback
     * @param {String} error Error message, if any.
     * @param {module:User} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * implement a basic uid and password requestion
     * @param {module://ExperienceApiApi~loginPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:User}
     */
    loginPost(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/xml'];
      let returnType = User;
      return this.apiClient.callApi(
        '/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
