/**
 * GLR 4 Schools
 * **NUMBER ONE TOPIC IS HOW BEST TO IMPLEMENT THESE API so that only data is segregated by school.**  Need to implement a form of authentication check PER SCHOOL. Is there a way to leverage the authorisation process implement by Group Call Xporter? This is the full set of API for GLR 4 Schools. Security definitions and exqmples need to be added.
 *
 * The version of the OpenAPI document: 1.0.1-oas3
 * Contact: john@greatlittlerewards.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import Page from './Page';

/**
 * The InlineResponse200 model module.
 * @module //InlineResponse200
 * @version 1.0.1-oas3
 */
class InlineResponse200 {
    /**
     * Constructs a new <code>InlineResponse200</code>.
     * @alias module://InlineResponse200
     * @extends module://Page
     * @implements module://Page
     */
    constructor() {
        Page.initialize(this);
        InlineResponse200.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {
    }

    /**
     * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module://InlineResponse200} obj Optional instance to populate.
     * @return {module://InlineResponse200} The populated <code>InlineResponse200</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200();
            Page.constructFromObject(data, obj);
            Page.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement Page interface:
/**
 * @member {Boolean} hasNextPage
 * @default false
 */
Page.prototype['hasNextPage'] = false;
/**
 * @member {Boolean} hasPreviousPage
 * @default false
 */
Page.prototype['hasPreviousPage'] = false;




export default InlineResponse200;

