/**
 * GLR 4 Schools
 * **NUMBER ONE TOPIC IS HOW BEST TO IMPLEMENT THESE API so that only data is segregated by school.**  Need to implement a form of authentication check PER SCHOOL. Is there a way to leverage the authorisation process implement by Group Call Xporter? This is the full set of API for GLR 4 Schools. Security definitions and exqmples need to be added.
 *
 * The version of the OpenAPI document: 1.0.1-oas3
 * Contact: john@greatlittlerewards.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';

/**
 * The Menu model module.
 * @module //Menu
 * @version 1.0.1-oas3
 */
class Menu {
    /**
     * Constructs a new <code>Menu</code>.
     * @alias module://Menu
     * @param name {String}
     */
    constructor(name) {

        Menu.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) {
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Menu</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module://Menu} obj Optional instance to populate.
     * @return {module://Menu} The populated <code>Menu</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Menu();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('menuItems')) {
                obj['menuItems'] = ApiClient.convertToType(data['menuItems'], [Menu]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Menu.prototype['name'] = undefined;

/**
 * @member {String} link
 */
Menu.prototype['link'] = undefined;

/**
 * @member {Array.<module:Menu>} menuItems
 */
Menu.prototype['menuItems'] = undefined;






export default Menu;

