/**
 * GLR 4 Schools
 * **NUMBER ONE TOPIC IS HOW BEST TO IMPLEMENT THESE API so that only data is segregated by school.**  Need to implement a form of authentication check PER SCHOOL. Is there a way to leverage the authorisation process implement by Group Call Xporter? This is the full set of API for GLR 4 Schools. Security definitions and exqmples need to be added.
 *
 * The version of the OpenAPI document: 1.0.1-oas3
 * Contact: john@greatlittlerewards.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "./ApiClient";
import LineItem from './LineItem';
import Order from './Order';

/**
* ProcessApi service.
* @module //ProcessApiApi
* @version 1.0.1-oas3
*/
export default class ProcessApiApi {

    /**
    * Constructs a new ProcessApiApi.
    * @alias module://ProcessApiApi
    * @class
    * @param {module:/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createNewCart operation.
     * @callback module://ProcessApiApi~createNewCartCallback
     * @param {String} error Error message, if any.
     * @param {module:Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Save these line items into a school order.
     * If there is a current order these items are added to it for the student. If not a new order is created for the school and these line items are added. We also validate that the student has enough points (would be good if that was also applied at GUI) and we deduct this from the students total. The updated values will be contained in the response object
     * @param {module:Body} body the current user AND an array of line items to be added to a school order
     * @param {module://ProcessApiApi~createNewCartCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:Order}
     */
    createNewCart(body, callback) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createNewCart");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Order;
      return this.apiClient.callApi(
        '/cart', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the findByStudentId operation.
     * @callback module://ProcessApiApi~findByStudentIdCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:LineItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get the list of line items for this student.
     * get the list of line items for this student from the current cart that belong to this student if any exist
     * @param {String} studentId the student we want the lineitems for. Example *5ce65f0f0e67a54e8fbefe77*
     * @param {module://ProcessApiApi~findByStudentIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:LineItem>}
     */
    findByStudentId(studentId, callback) {
      let postBody = null;
      // verify the required parameter 'studentId' is set
      if (studentId === undefined || studentId === null) {
        throw new Error("Missing the required parameter 'studentId' when calling findByStudentId");
      }

      let pathParams = {
      };
      let queryParams = {
        'studentId': studentId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [LineItem];
      return this.apiClient.callApi(
        '/cart/findByStudentId', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCurrentForSchool operation.
     * @callback module://ProcessApiApi~getCurrentForSchoolCallback
     * @param {String} error Error message, if any.
     * @param {module:Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get the Current Open Order for a school if one exists
     * @param {String} schoolId the school we want the orders for. Example 5ce3c2d80e67a54e8fbefe74
     * @param {module://ProcessApiApi~getCurrentForSchoolCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:Order}
     */
    getCurrentForSchool(schoolId, callback) {
      let postBody = null;
      // verify the required parameter 'schoolId' is set
      if (schoolId === undefined || schoolId === null) {
        throw new Error("Missing the required parameter 'schoolId' when calling getCurrentForSchool");
      }

      let pathParams = {
      };
      let queryParams = {
        'schoolId': schoolId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Order;
      return this.apiClient.callApi(
        '/store/order/getCurrentForSchool', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getOrderById operation.
     * @callback module://ProcessApiApi~getOrderByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find order by ID.
     * **Get a single Order** Returns a single order.
     * @param {String} orderId ID of order to return. Example 5cfe314591ae1d279a6961a1
     * @param {module://ProcessApiApi~getOrderByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:Order}
     */
    getOrderById(orderId, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling getOrderById");
      }

      let pathParams = {
        'orderId': orderId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Order;
      return this.apiClient.callApi(
        '/store/order/{orderId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the placeOrder operation.
     * @callback module://ProcessApiApi~placeOrderCallback
     * @param {String} error Error message, if any.
     * @param {module:Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * add a new order
     * Add a new order. We need to think about how this is called. an order only needs to be created if one does not already exist but there is a chance that two students could call this in some sort of race condition.
     * @param {module:Order} order create a new order
     * @param {module://ProcessApiApi~placeOrderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:Order}
     */
    placeOrder(order, callback) {
      let postBody = order;
      // verify the required parameter 'order' is set
      if (order === undefined || order === null) {
        throw new Error("Missing the required parameter 'order' when calling placeOrder");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/xml'];
      let returnType = Order;
      return this.apiClient.callApi(
        '/store/order', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the storeOrderGet operation.
     * @callback module://ProcessApiApi~storeOrderGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:Order>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get a list of all orders - only usable by GLR Admin
     * returns an array of all orders that meet the parameters THAT NEED TO BE DEFINED!
     * @param {String} schoolId the school we want the orders for.
     * @param {Object} opts Optional parameters
     * @param {Date} opts.fromDate the from which we want to retrieve forward a particular schools orders. example 2019-10-01
     * @param {module://ProcessApiApi~storeOrderGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:Order>}
     */
    storeOrderGet(schoolId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'schoolId' is set
      if (schoolId === undefined || schoolId === null) {
        throw new Error("Missing the required parameter 'schoolId' when calling storeOrderGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'schoolId': schoolId,
        'fromDate': opts['fromDate']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Order];
      return this.apiClient.callApi(
        '/store/order', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateCart operation.
     * @callback module://ProcessApiApi~updateCartCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update line items
     * amend the items of mine that belong to an open school order
     * @param {module://ProcessApiApi~updateCartCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updateCart(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'basicAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/cart', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateOrder operation.
     * @callback module://ProcessApiApi~updateOrderCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update an existing Order (assuming the order is held in mongo and not in shopify)
     * @param {module:Order} order Order object that needs to be added to the store
     * @param {module://ProcessApiApi~updateOrderCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updateOrder(order, callback) {
      let postBody = order;
      // verify the required parameter 'order' is set
      if (order === undefined || order === null) {
        throw new Error("Missing the required parameter 'order' when calling updateOrder");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'basicAuth'];
      let contentTypes = ['application/json', 'application/xml'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/store/order', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
