/**
 * GLR 4 Schools
 * **NUMBER ONE TOPIC IS HOW BEST TO IMPLEMENT THESE API so that only data is segregated by school.**  Need to implement a form of authentication check PER SCHOOL. Is there a way to leverage the authorisation process implement by Group Call Xporter? This is the full set of API for GLR 4 Schools. Security definitions and exqmples need to be added.
 *
 * The version of the OpenAPI document: 1.0.1-oas3
 * Contact: john@greatlittlerewards.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';

/**
 * The ProductImage model module.
 * @module //ProductImage
 * @version 1.0.1-oas3
 */
class ProductImage {
    /**
     * Constructs a new <code>ProductImage</code>.
     * @alias module://ProductImage
     * @param shopifyId {String}
     */
    constructor(shopifyId) {

        ProductImage.initialize(this, shopifyId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, shopifyId) {
        obj['shopifyId'] = shopifyId;
    }

    /**
     * Constructs a <code>ProductImage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module://ProductImage} obj Optional instance to populate.
     * @return {module://ProductImage} The populated <code>ProductImage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductImage();

            if (data.hasOwnProperty('shopifyId')) {
                obj['shopifyId'] = ApiClient.convertToType(data['shopifyId'], 'String');
            }
            if (data.hasOwnProperty('altText')) {
                obj['altText'] = ApiClient.convertToType(data['altText'], 'String');
            }
            if (data.hasOwnProperty('originalSource')) {
                obj['originalSource'] = ApiClient.convertToType(data['originalSource'], 'String');
            }
            if (data.hasOwnProperty('src')) {
                obj['src'] = ApiClient.convertToType(data['src'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} shopifyId
 */
ProductImage.prototype['shopifyId'] = undefined;

/**
 * @member {String} altText
 */
ProductImage.prototype['altText'] = undefined;

/**
 * @member {String} originalSource
 */
ProductImage.prototype['originalSource'] = undefined;

/**
 * @member {String} src
 */
ProductImage.prototype['src'] = undefined;






export default ProductImage;

