/**
 * GLR 4 Schools
 * **NUMBER ONE TOPIC IS HOW BEST TO IMPLEMENT THESE API so that only data is segregated by school.**  Need to implement a form of authentication check PER SCHOOL. Is there a way to leverage the authorisation process implement by Group Call Xporter? This is the full set of API for GLR 4 Schools. Security definitions and exqmples need to be added.
 *
 * The version of the OpenAPI document: 1.0.1-oas3
 * Contact: john@greatlittlerewards.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';

/**
 * The School model module.
 * @module //School
 * @version 1.0.1-oas3
 */
class School {
    /**
     * Constructs a new <code>School</code>.
     * @alias module://School
     * @param id {String}
     * @param name {String}
     */
    constructor(id, name) {

        School.initialize(this, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name) {
        obj['Id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>School</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module://School} obj Optional instance to populate.
     * @return {module://School} The populated <code>School</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new School();

            if (data.hasOwnProperty('Id')) {
                obj['Id'] = ApiClient.convertToType(data['Id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('schoolLogoURL')) {
                obj['schoolLogoURL'] = ApiClient.convertToType(data['schoolLogoURL'], 'String');
            }
            if (data.hasOwnProperty('head')) {
                obj['head'] = ApiClient.convertToType(data['head'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} Id
 */
School.prototype['Id'] = undefined;

/**
 * @member {String} name
 */
School.prototype['name'] = undefined;

/**
 * @member {String} schoolLogoURL
 */
School.prototype['schoolLogoURL'] = undefined;

/**
 * @member {String} head
 */
School.prototype['head'] = undefined;

/**
 * @member {String} phone
 */
School.prototype['phone'] = undefined;

/**
 * @member {String} address
 */
School.prototype['address'] = undefined;






export default School;

