/**
 * GLR 4 Schools
 * **NUMBER ONE TOPIC IS HOW BEST TO IMPLEMENT THESE API so that only data is segregated by school.**  Need to implement a form of authentication check PER SCHOOL. Is there a way to leverage the authorisation process implement by Group Call Xporter? This is the full set of API for GLR 4 Schools. Security definitions and exqmples need to be added.
 *
 * The version of the OpenAPI document: 1.0.1-oas3
 * Contact: john@greatlittlerewards.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "./ApiClient";
import Student from './Student';

/**
* Student service.
* @module //StudentApi
* @version 1.0.1-oas3
*/
export default class StudentApi {

    /**
    * Constructs a new StudentApi.
    * @alias module://StudentApi
    * @class
    * @param {module:/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getStudentById operation.
     * @callback module://StudentApi~getStudentByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:Student} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find student by ID
     * **Get Student** Returns a single student.
     * @param {String} xSchoolToken
     * @param {String} studentId ID of student to return
     * @param {module://StudentApi~getStudentByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:Student}
     */
    getStudentById(xSchoolToken, studentId, callback) {
      let postBody = null;
      // verify the required parameter 'xSchoolToken' is set
      if (xSchoolToken === undefined || xSchoolToken === null) {
        throw new Error("Missing the required parameter 'xSchoolToken' when calling getStudentById");
      }
      // verify the required parameter 'studentId' is set
      if (studentId === undefined || studentId === null) {
        throw new Error("Missing the required parameter 'studentId' when calling getStudentById");
      }

      let pathParams = {
        'studentId': studentId
      };
      let queryParams = {
      };
      let headerParams = {
        'X-School-Token': xSchoolToken
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Student;
      return this.apiClient.callApi(
        '/student/{studentId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
