module.exports = {
    googleClientID: process.env.GOOGLE_CLIENT_ID,
    googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
    mongoURI: process.env.MONGO_URI,
    cookieKey: process.env.COOKIE_KEY,
    stripePublishableKey: process.env.STRIPE_PUBLISHABLE_KEY,
    stripeSecretKey:process.env.STRIPE_SECRET_KEY,
    sendgridKey:process.env.SENDGRID_KEY,
    redirectDomain:process.env.REDIRECT_DOMAIN,
    shopifyAPIKey:process.env.SHOPIFY_API_KEY,
    shopifyAPIPassword:process.env.SHOPIFY_API_PASSWORD,
    shopifySharedSecret:process.env.SHOPIFY_SHARED_SECRET,
    shopifyStoreName:process.env.SHOPIFY_STORE_NAME,
    shopifyAPIVersion:process.env.SHOPIFY_API_VERSION,
    shopifyCollectionId: process.env.SHOPIFY_COLLECTION_ID,
    shopifyMetaNamespace: process.env.SHOPIFY_META_NAMESPACE,
    shopifyMetaKey: process.env.SHOPIFY_META_KEY,
    glrAPIGateway: process.env.GLR_API_GATEAWAY,
    glrAPIGatewayKey: process.env.GLR_API_GATEAWAY_KEY,
    glrAPIProduct: process.env.GLR_API_PRODUCT
};
