const mongoose = require("mongoose");
const { Schema } = mongoose;

const XODStudentSchema = new Schema({

  Id : {type: String, required: true},
  XID : {type: String, required: true},
  ExternalId : {type: String, required: true},
  idaasId : {type: String, required: false},
  Forename : {type: String, required: false},
  Surname : {type: String, required: false},
  DisplayName:{type: String, required: false},
  AdmissionNo: {type: String, required: false},
  Gender: {type: String, required: false},
  RegGroupId: {type: String, required: false},
  RegGroup: {type: String, required: false},
  YearGroupId: {type: String, required: false},
  YearGroup: {type: String, required: false},
  HouseGroupId:{type: String, required: false},
  HouseGroup : {type: String, required: false},
  WorkEmail : {type: String, required: false},
  IdaasEmail :{type: String, required: false},
  UPN : {type: String, required: false},
  formerUPN: {type: String, required: false},
  Photo: {type: Buffer, required: false},
  DateofBirth : {type: Date, required: false},
  UniqueLearnerNumber: {type: String, required: false},
  MiddleName : {type: String, required: false},
  EnrolmentStatus : {type: String, required: false},
  Boarder : {type: Number, required: false},
  LegalForename : {type: String, required: false},
  LegalSurname : {type: String, required: false},
  EntryDate : {type: String, required: false},
  LeavingDate : {type: Date, required: false},
  Destination : {type: String, required: false},
  DestinationStartDate : {type: Date, required: false},
  ReasonForLeaving : {type: String, required: false},
  SENProvision : {type: String, required: false},
  FsmEligible : {type: Number, required: false},
  FsmEndDate : {type: Date, required: false},
  UniformAllowance : {type: Number, required: false},
  PupilPremium : {type: Number, required: false},
  YSSA : {type: String, required: false},
  EAL : {type: Number, required: false},
  FSMEver6 : {type: Number, required: false},
  Gifted : {type: Number, required: false},
  ServiceChild : {type: String, required: false},
  ServiceChildSource : {type: String, required: false},
  InLeaCare : {type: Number, required: false},
  LeaCareAuthority : {type: String, required: false},
  EverInCare : {type: Number, required: false},
  IsYoungCarer : {type: Number, required: false},
  AsylumStatus : {type: String, required: false},
  OnReport : {type: String, required: false},
  ReligionCode : {type: String, required: false},
  Religion : {type: String, required: false},
  EthnicityCode : {type: String, required: false},
  Ethnicity : {type: String, required: false},
  EthnicitySource : {type: String, required: false},
  HomeLanguage : {type: String, required: false},
  HomeLanguageCode : {type: String, required: false},
  FirstLanguage : {type: String, required: false},
  FirstLanguageCode : {type: String, required: false},
  FirstLanguageSource : {type: String, required: false},
  EnglishProficiencyLevel : {type: String, required: false},
  NationalIdentity : {type: String, required: false},
  Nationality : {type: String, required: false},
  ModeOfTravel:  {type: String, required: false},
  IsTraveller :{type: String, required: false},
  TravellerSource: {type: String, required: false},
  ParentalSalutation: {type: String, required: false},
  AddressBlock :{type: String, required: false},
  HouseNo : {type: String, required: false},
  HouseName :{type: String, required: false},
  Apartment : {type: String, required: false},
  Street : {type: String, required: false},
  District : {type: String, required: false},
  TownOrCity : {type: String, required: false},
  County : {type: String, required: false},
  PostCode : {type: String, required: false},
  Country : {type: String, required: false},
  AttStatsStartDate:  {type: Date, required: false},
  AttStatsEndDate: {type: Date, required: false},
  NumPossMarks: {type: Number, required: false},
  NumPresMarks: {type: Number, required: false},
  NumAEAMarks: {type: Number, required: false},
  NumAuthAbsMarks:{type: Number, required: false},
  NumUnauthAbsMarks: {type: Number, required: false},
  NumMissMarks: {type: Number, required: false},
  NumLateMarks: {type: Number, required: false},
  NumLateBeforeRegMarks: {type: Number, required: false},
  AttMarksStartDate: {type: Date, required: false},
  AttMarksEndDate: {type: Date, required: false},
  Marks: {type: String, required: false},
  StudentStatus : {type: String, required: false},
  PartTime : {type: Number, required: false},
  YearTaughtIn : {type: String, required: false},
  KeyStage : {type: String, required: false},
  LastUpdated : {type: Date, required: false},
  RowHash :{type: String, required: false},
  GroupIds: {type: String, required: false},
  GroupXIDs: {type: String, required: false},
  GroupIdaasIds: {type: String, required: false},
  ParentIdaasIds: {type: String, required: false},
  ParentXIDs: {type: String, required: false},
});

//mongoose.model("xodstudents", XODStudentSchema);

module.exports = XODStudentSchema;
